/**
 * Core TypeScript types for LoopMagic Deal Underwriting
 * Based on LoopNet's JSON-LD structured data (schema.org RealEstateListing)
 */

// ============================================================================
// Property Data (Scraped from LoopNet)
// ============================================================================

export interface PropertyData {
  // Core identification
  url: string;
  listingId: string;
  propertyName: string;
  address: Address;

  // Financial data
  price: number;
  priceFormatted: string; // e.g., "$8,000,000"
  pricePerUnit?: number;
  pricePerSF?: number;
  capRate?: string; // e.g., "5.5%"
  noi?: number; // Net Operating Income
  grossIncome?: number;

  // Property details
  propertyType: string; // e.g., "Multifamily", "Office", "Retail"
  propertySubtype?: string; // e.g., "Apartment", "Medical Office"
  buildingSize: number; // in square feet
  buildingSizeFormatted: string; // e.g., "19,235 SF"
  lotSize?: string; // e.g., "0.55 AC"
  units?: number; // Number of units (for multifamily)

  // Building characteristics
  yearBuilt?: number;
  yearRenovated?: number;
  numberOfStories?: number;
  buildingClass?: string; // e.g., "A", "B", "C"
  occupancy?: string; // e.g., "100%"
  zoning?: string;

  // Amenities and features
  amenities?: string[];
  parkingRatio?: string;

  // Additional metrics
  walkScore?: number;

  // Marketing
  description: string;
  photos: Photo[];

  // Broker information
  brokers: Broker[];

  // Metadata
  dateModified?: string; // ISO date
  dateScraped: string; // ISO date

  // Raw data for debugging
  rawJSON?: any;
}

export interface Address {
  streetAddress: string;
  city: string;
  state: string;
  zipCode: string;
  fullAddress: string; // Formatted: "2162 SW 14th Ter, Miami, FL 33145"
  country?: string;
}

export interface Photo {
  url: string;
  width?: number;
  height?: number;
  caption?: string;
}

export interface Broker {
  name: string;
  company?: string;
  photo?: string;
  city?: string;
  state?: string;
}

// ============================================================================
// Analysis Data (Generated by Claude)
// ============================================================================

export interface AnalysisResult {
  // Executive summary
  summary: string;
  recommendation: 'Strong Buy' | 'Buy' | 'Hold' | 'Pass' | 'Avoid';
  confidenceLevel: 'High' | 'Medium' | 'Low';

  // Financial analysis
  financialMetrics: {
    estimatedROI?: string;
    cashOnCashReturn?: string;
    debtServiceCoverageRatio?: string;
    capRateAnalysis?: string;
    comparableMarketAnalysis?: string;
  };

  // Market analysis
  marketInsights: {
    locationQuality: string;
    marketTrends: string;
    competitivePosition: string;
    growthPotential: string;
  };

  // Risk assessment
  risks: {
    summary: string;
    majorConcerns: string[];
    mitigationStrategies: string[];
  };

  // Opportunities
  valueAddOpportunities: string[];

  // Key takeaways (bullet points)
  keyTakeaways: string[];

  // Detailed analysis (narrative)
  detailedAnalysis: string;

  // Metadata
  analysisDate: string; // ISO date
  modelUsed: string; // e.g., "claude-sonnet-4-5-20250929"
  tokensUsed?: number;
}

// ============================================================================
// API Request/Response Types
// ============================================================================

export interface AnalyzeRequest {
  loopnetUrl: string;
}

export interface AnalyzeResponse {
  success: boolean;
  data?: {
    property: PropertyData;
    analysis: AnalysisResult;
    excel: {
      downloadUrl: string;
      filename: string;
      expiresAt: string; // ISO date (24 hours from now)
    };
  };
  error?: {
    code: string;
    message: string;
    details?: any;
  };
  metadata: {
    requestId: string;
    timestamp: string;
    processingTimeMs: number;
    creditsUsed: {
      scraping: number; // ScrapingBee credits
      aiTokens: number; // Claude API tokens
    };
  };
}

// ============================================================================
// Scraping Types
// ============================================================================

export interface ScrapingResult {
  success: boolean;
  html?: string;
  error?: string;
  creditsUsed?: number;
  metadata?: {
    scrapedAt: string;
    responseTimeMs: number;
  };
}

// ============================================================================
// Excel Generation Types
// ============================================================================

export interface ExcelGenerationOptions {
  property: PropertyData;
  analysis: AnalysisResult;
  includePhotos?: boolean; // Default: true, limit to 5
  includeCharts?: boolean; // Default: false (Phase 1 feature)
}

export interface ExcelGenerationResult {
  success: boolean;
  buffer?: Buffer;
  filename: string;
  error?: string;
}

// ============================================================================
// Error Types
// ============================================================================

export class LoopMagicError extends Error {
  constructor(
    message: string,
    public code: string,
    public statusCode: number = 500,
    public details?: any
  ) {
    super(message);
    this.name = 'LoopMagicError';
  }
}

export class ScrapingError extends LoopMagicError {
  constructor(message: string, details?: any) {
    super(message, 'SCRAPING_ERROR', 500, details);
    this.name = 'ScrapingError';
  }
}

export class AnalysisError extends LoopMagicError {
  constructor(message: string, details?: any) {
    super(message, 'ANALYSIS_ERROR', 500, details);
    this.name = 'AnalysisError';
  }
}

export class ExcelGenerationError extends LoopMagicError {
  constructor(message: string, details?: any) {
    super(message, 'EXCEL_ERROR', 500, details);
    this.name = 'ExcelGenerationError';
  }
}
